### ISSUE TITLE
Πολιτική Χρήσης Plugin

### ISSUE THREAD

**Issue by pmytilin1984** [avlabedu/www#3]
Το Wordpress προσφέρει πλούσιο οικοσύστημα plugin που καλύπτει πολλές από τις υπάρχουσες λειτουργικότητες.
Το θετικό της χρήσης των plugin είναι η ταχύτητα του development και η ευκολία διαχείρισης και επεξεργασίας από το backend.
Το αρνητικό είναι η εν δυνάμει αργή ενημέρωσή τους με security updates και η κατά περίπτωση προσθήκη περισσότερων attack vectors. Παρά ταύτα, ιδιαίτερα δημοφιλή plugins με εκατοντάδες χιλιάδες installs μάλον παρέχει περισσότερη ασφάλεια, παρά τη θέτει σε κίνδυνο.
Από τη μέχρι τώρα εμπειρία μου σε σελίδες που έχω αναπτύξει ή έχω διαχειριστεί ύστερα από ανάπτυξή τους από άλλον developer είναι ότι χρησιμοποιούνται κατά κόρον.

Κατά πόσο θέλουμε να περιοριστούμε στο stock wordpress και την εσωτερική ανάπτυξη πρόσθετων λειτουργιών;
Θα ήθελα την εμπειρία και την τεχνική κατάρτισή σας πάνω στο ζήτημα.

**Comment by csevast** [comment]
Δεν έχω πλέον επαφή με την τρέχουσα κατάσταση. Θεωρώ όμως, ότι για την ανάπτυξη του πληροφοριακού μέρους της ιστοσελίδας πρέπειν να εφαρμόσουμε τα συνήθη, κάνοντας ό,τι οι περισσότεροι, δηλαδή να χρησιμοποιήσουμε plugins, αρκεί να εκτιμηθούν η ασφάλειά τους.
